### ISSUE TITLE
Code vulnerable to SQL injections

### ISSUE THREAD

**Issue by Hamz-a** [ahmed9677/PHPtoDev#1]
The code is vulnerable to SQL injections. For information about SQL injections, consult the following OWASP page: https://www.owasp.org/index.php/SQL_Injection

It is advisable to use prepared statements. The following Stackoverflow answer gives a basic example: https://stackoverflow.com/a/60496
The following video explains it well: https://www.youtube.com/watch?v=nLinqtCfhKY

**Comment by AlgUp** [comment]
Hey , i'll go and fix it , i know about SQL injections , this code was made in 2012 , and i post it directly , thnx for the report ;)

**Comment by AlgUp** [comment]
Hey, the SQL injections was closed but in the simple way by creating a simple function that help adding security , for the moment it's up to the developpeur, on the next days i'll add a hole large of change :)
